server:
  port: 8080

spring:
  application:
    name: hrms-backend
  datasource:
    url: jdbc:mysql://localhost:3306/hrms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 212324
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hrms.entity
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

hrms:
  auth:
    secret: hrms-demo-secret-change-in-production
    token-valid-hours: 8
